[workspace]
resolver = "2"
members = ["assertr", "assertr-derive"]
default-members = ["assertr"]

[workspace.dependencies]
proc-macro-type-name = "0.1.0"
darling = "0.20.10"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.72", features = ["extra-traits"] }
